version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  builder: html

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .